# Generated by Django 6.0.3 on 2026-03-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrauser',
            old_name='name',
            new_name='fullname',
        ),
    ]
