# Generated by Django 6.0.3 on 2026-04-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_instrauser_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='posts/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagged_users', models.ManyToManyField(blank=True, related_name='tagged_user', to='myapp.instrauser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instrauser')),
            ],
        ),
    ]
