# Generated by Django 6.0.3 on 2026-04-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='instaPost',
        ),
        migrations.RenameModel(
            old_name='instrauser',
            new_name='instauser',
        ),
        migrations.CreateModel(
            name='FollowUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='myapp.instauser')),
                ('following_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_person', to='myapp.instauser')),
            ],
        ),
    ]
