# Generated by Django 6.0.3 on 2026-04-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_fk', to='myapp.instapost'),
        ),
    ]
