# Generated by Django 6.0.3 on 2026-04-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_like_dislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaReels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='InstaReels/')),
                ('thumbnails', models.ImageField(blank=True, null=True, upload_to='InstaReels_thumbnails/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tagged_users', models.ManyToManyField(blank=True, related_name='tagged_post', to='myapp.instauser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser')),
            ],
        ),
    ]
