# Generated by Django 6.0.3 on 2026-04-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_instareels'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='otp',
            field=models.PositiveIntegerField(default=987),
        ),
    ]
