# Generated by Django 6.0.3 on 2026-05-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.instareels'),
        ),
        migrations.AddField(
            model_name='like_dislike',
            name='reel_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_reel', to='myapp.instareels'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.instapost'),
        ),
        migrations.AlterField(
            model_name='like_dislike',
            name='post_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='myapp.instapost'),
        ),
    ]
