# Generated by Django 6.0.3 on 2026-05-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_comment_reel_like_dislike_reel_fk_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='stories/')),
                ('is_video', models.BooleanField(default=False)),
                ('music', models.FileField(blank=True, null=True, upload_to='story_music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='myapp.instauser')),
            ],
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='myapp.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instauser')),
            ],
            options={
                'unique_together': {('story', 'user')},
            },
        ),
    ]
