# Generated by Django 6.0.3 on 2026-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_story_storyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyview',
            name='story',
        ),
        migrations.AlterUniqueTogether(
            name='storyview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storyview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reel',
        ),
        migrations.RemoveField(
            model_name='like_dislike',
            name='reel_fk',
        ),
        migrations.AddField(
            model_name='instauser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryView',
        ),
    ]
